Add media page with style and images
Noelierx/GameHer pull request #100
Opened 2020-10-30 10:23 UTC by karlyn33

The essential is in the page and fix issues #89 

I did my best for the Css but i'm not the best for that.

2020-11-02 19:49 UTC, karlyn33 commented
@Noelierx Is still possible to verify my last 2 pull request, i was tryng to acheve the Hacktoberfest Challenge, dunno if it will still count :(

2020-11-03 13:10 UTC, Noelierx commented
@karlyn33 I'm so sorry, I had so much stuff to do, but I just add the required labels, I really hope it will count. 
PR doesn't need to get merge or verified right away, they just need to have the required labels even if they're merged months later it will still count.

2020-11-06 13:51 UTC, Noelierx requested changes

2020-11-06 13:51 UTC, Noelierx commented on templates/common/titleBannerBigRed.html.twig
> +<section class="titleBannerNoBackground {{ className | default('') }}">
I don't think it's useful to create a full new common template for this. 
This kind of component should stay the most generic possible.
In my opinion, it's best to stick with `titleBanner.html.twig` and update the style ( className can be modified later so we can change the background color here).

2021-05-06 14:21 UTC, closed without merging