Add field to set publication time
Noelierx/GameHer pull request #94
Opened 2020-10-05 23:24 UTC by Sonny812

Closes #74

2020-10-06 09:29 UTC, Noelierx commented
Hello @Sonny812 Thank you a lot for your pull request, we just need to verify it, but don't worry even if this PR isn't merged at the end of your counter, it will still be a part for the Hacktoberfest and your personal counter!

2020-10-22 09:27 UTC, chypriote requested changes
So minor formatting problems (use editorconfig to avoid those)

@Noelierx should test wether the feature works correctly

2020-10-22 09:27 UTC, chypriote commented on src/Form/Blog/PostType.php
> +	/**
Please fix the indentation

2020-10-22 09:27 UTC, chypriote commented on src/Form/DateTimeType.php
> + * @author    Nickolay Mikhaylov <sonny@milton.pro>
We do not add copyrights on our files

2020-10-22 09:27 UTC, chypriote commented on src/Form/DateTimeType.php
> + * Date time type
Please remove the comments here and on line 24

2020-10-22 09:27 UTC, chypriote commented on src/Form/Transformer/DateTimeModelTransformer.php
> + * @copyright Copyright (c) 2020, GameHer
Same here

2020-10-22 20:35 UTC, chypriote approved these changes

2026-07-16 21:42 UTC, closed without merging